### ISSUE TITLE
Selvitetään minimum viable product

### ISSUE THREAD

**Issue by xylix** [funktionaalinen-graafinen-kieli/backlogs#3]
2 hahmoa, palikkakoodaus, näppäinpainallusten lukeminen

**Comment by Hannav** [comment]
Palikkakoodaus, 2 hahmoa, koodin ajaminen

**Comment by Hannav** [comment]
MVP: Linkki-kerhon Keräilypeli malliksi: Pelissä yksi hahmo ja aarre. Hahmo liikkuu hiirellä tai nuolinäppäimillä, tarkoitus mennä aarteen luokse, jolloin pisteitä tulee yksi lisää.

Linkki malliin: https://linkki.cs.helsinki.fi/cgi-bin/debbie-action-materiaalit?syn=&ohjelmointikieli=Scratch

**Comment by Hannav** [comment]
https://linkki.cs.helsinki.fi/cgi-bin/debbie-action-materiaalit?syn=&ohjelmointikieli=Scratch
