### ISSUE TITLE
Get palikan dropdown menu bugeja

### ISSUE THREAD

**Issue by nicohi** [funktionaalinen-graafinen-kieli/backlogs#66]
- [x] ei generoi koodia
- [x] entityt päivittyvät vasta kun get palikan luo

**Comment by xylix** [comment]
`Ignoring non-existent input key in block funkly_get` konsolivirhe varmaan liittyy

**Comment by xylix** [comment]
Nykyisessä developin versiossa get toimii muuten mutta outputista puuttuvat hipsut ("e1_x" sijasta outputtaa e1_x).

**Comment by xylix** [comment]
Muuten toimii, mutta päivitin "default" xml:n uuteen ja e2 koodissa on nyt vielä joku bugi liikkeelle lähdössä.
