### ISSUE TITLE
Save ei toimi: Pelin pitää olla käynnistetty, muuten tulee "Editor is null", vaikka olisi liikuttanut palikoita. Myös muiden nappien toiminta menussa.

### ISSUE THREAD

**Issue by xylix** [funktionaalinen-graafinen-kieli/backlogs#68]
Pelin pitää olla käynnistetty, muuten tulee "Editor is null", vaikka olisi liikuttanut palikoita.

**Comment by Hannav** [comment]
debug print lisätty, jotta ei kaadu alkuperäisen issuen takia
